version: "3"
services:
  postgres:
    image: postgres:latest
    volumes: 
      - db-data:/data/db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345asdf"
      POSTGRES_DB: techwondoefsd
    ports:
      - "5432-5432"

  backend:
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  db-data:
    driver: local